### ISSUE TITLE
Error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by NishantDesai1306** [vslala/angular2-boiler-plate#1]
After cloning your boiler plate and executing `npm run start` script I get this error in browser's console, Although the app started properly and displayed msg "My second Angular 2 App"

**Comment by vslala** [comment]
It's working fine on my pc. Below is the screenshot for the same. Maybe you should try `npm install` first. 

![image](https://cloud.githubusercontent.com/assets/11189528/19395161/d3acc6b2-9259-11e6-9654-6555f5589601.png)
